oldFilename: Aboveground_biomass_PgC.csv
indicatorName: Aboveground biomass (PgC)
date: 29/05/2017
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Aboveground biomass
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'Yes'
pristineValue: .na.real
allgoneValue: 0
notes: See Google Doc for justification of Pristine value
