oldFilename: BHI_all_taxa.csv
indicatorName: All-taxa richness (BILBI) - hotspots
date: 29/10/2018
core_highlight_other: Core
whole_part: Part
high_low: High
nameForPlot: BHI (species persisting) - Hotspots
ebvClass: Species populations
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: ''
