oldFilename: BHI_inverts.csv
indicatorName: Invertebrate habitat (BILBI)
date: 29/10/2018
core_highlight_other: Core
whole_part: Part
high_low: High
nameForPlot: BHI (invertebrate habitat integrity)
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: ''
