oldFilename: BHI_plants.csv
indicatorName: Plant habitat (BILBI)
date: 01/10/2018
core_highlight_other: Core
whole_part: Part
high_low: High
nameForPlot: BHI (plant habitat integrity)
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: ''
