oldFilename: BHI_vertebrates.csv
indicatorName: Vertebrate habitat (BILBI)
date: 26/10/2018
core_highlight_other: Core
whole_part: Part
high_low: High
nameForPlot: BHI (vertebrate habitat integrity)
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: ''
