oldFilename: Global_NPP-weighted_BII_LUH2.csv
indicatorName: Biodiversity Intactness Index (global)
date: 17/03/2018
core_highlight_other: Core
whole_part: Whole
high_low: High
nameForPlot: Biodiversity Intactness Index (overall)
ebvClass: Community composition
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: AP typed these in from the projection output
