oldFilename: ipl_bii.csv
indicatorName: BII (Indigenous Lands)
date: 19/11/2018
core_highlight_other: Core
whole_part: Part
high_low: High
nameForPlot: Biodiversity Intactness Index (Indigenous Lands)
ebvClass: Community composition
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: AP typed these in from the projection output
