oldFilename: global_BII_tropical_forest.csv
indicatorName: BII tropical forest (Hotspots)
date: 21/11/2018
core_highlight_other: Core
whole_part: Part
high_low: High
nameForPlot: Tropical forest BII (hotspots)
ebvClass: Community composition
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: ''
