oldFilename: Biomass_turnover_rate.csv
indicatorName: Biomass turnover rate
date: 28/03/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Biomass turnover rate
ebvClass: Ecosystem function
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 0.0724638
allgoneValue: 0
notes: Pristine value is from supp mat, table S11
