oldFilename: csar_iDiv_Allbirds_Localtoglobal.csv
indicatorName: cSAR Local results aggregated to Global all birds
date: 01/01/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Bird species per grid cell (cSAR)
ebvClass: Community composition
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: .na.real
allgoneValue: 0
notes: ''
