oldFilename: coastal_C_sink_habitats.csv
indicatorName: Extent and condition of natural coastal carbon sinks
date: 28/03/2018
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: Coastal carbon-rich habitat
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'Yes'
underpinNCP: 'Yes'
pristineValue: .na.real
allgoneValue: 0
notes: coastal_C_sink_habitats.csv
