oldFilename: Trendy_Indicators_20181104_1860to2015.csv
indicatorName: Evapotranspiration (1000km3/year)
date: 03/11/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Evapotranspiration (model ensemble)
ebvClass: Ecosystem function
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 63.5391429
allgoneValue: 0
notes: Pristine value is for 1860, the first year of the model run
