oldFilename: Marine_wilderness_Jones2018.csv
indicatorName: Marine wilderness %
date: 15/10/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Extent of marine wilderness
ebvClass: Ecosystem structure
representative_fundamental: 'No'
sensitive: 'Yes'
underpinNCP: 'No'
pristineValue: 100.0
allgoneValue: 0
notes: ''
