oldFilename: ExtentOfSuitableHabitatMammals.csv
indicatorName: Extent of Suitable Habitat
date: 07/08/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Extent of suitable habitat (mammals)
ebvClass: Species populations
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: .na.real
allgoneValue: 0
notes: This is for all terrestrial mammals
