oldFilename: FractionOceanNotFished.csv
indicatorName: Ocean not fished in given year
date: 27/03/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Fraction of ocean not fished per year
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'Yes'
underpinNCP: 'No'
pristineValue: 100.0
allgoneValue: 0
notes: Value from paper; other years had less good sampling
