oldFilename: Madingley_functional_richness_revised1018.csv
indicatorName: Madingley functional richness (50%quantile)
date: 10/10/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Functional richness (Madingley)
ebvClass: Species traits
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: .na.real
allgoneValue: 0
notes: ''
