oldFilename: Extent_UoA_reshaped.csv
indicatorName: Land not cropland or urban - temperate grassland
date: ''
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: 'Land not cultivated or urban (UoA: temperate grassland)'
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 11.193144
allgoneValue: 0
notes: ''
