oldFilename: Extent_UoA_reshaped.csv
indicatorName: Land not cropland or urban - tropical grassland
date: ''
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: 'Land not cultivated or urban (UoA: tropical grassland)'
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 20.177549
allgoneValue: 0
notes: ''
