oldFilename: Extent_UoA_reshaped.csv
indicatorName: Land not cropland or urban (overall)
date: 26/03/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Land not cultivated or urban (global)
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 131.569905
allgoneValue: 0
notes: ''
