oldFilename: Extent_UoA_reshaped.csv
indicatorName: Land not cropland or urban - deserts & drylands
date: ''
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: 'Land not cultivated or urban (UoA: desert & dryland)'
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 27.885678
allgoneValue: 0
notes: ''
