oldFilename: Extent_UoA_reshaped.csv
indicatorName: Land not cropland or urban - tundra & mountains
date: ''
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: 'Land not cultivated or urban (UoA: tundra & mountains)'
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 13.554884
allgoneValue: 0
notes: ''
