oldFilename: Extent_UoA_reshaped.csv
indicatorName: Land not cropland or urban - hotspot
date: ''
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: Land not cultivated or urban (Hotspots)
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 18.13
allgoneValue: 0
notes: ''
