oldFilename: Extent_UoA_reshaped.csv
indicatorName: Land not cropland or urban - indigenous land
date: ''
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: Land not cultivated or urban (Indigenous Lands)
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 38.12
allgoneValue: 0
notes: ''
