oldFilename: Extent_UoA_reshaped.csv
indicatorName: Land not cropland or urban - Mediterranean forests
date: ''
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: 'Land not cultivated or urban (UoA: Mediterranean forest)'
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 3.220386
allgoneValue: 0
notes: ''
