oldFilename:
- LAI.csv
- LAI_gimms3g.csv
indicatorName:
- Leaf Area Index
- Leaf Area Index
date:
- 29/03/2018
- 26/10/2018
core_highlight_other:
- Other
- Other
whole_part:
- Whole
- Whole
high_low:
- High
- High
nameForPlot:
- Leaf Area Index
- Leaf Area Index
ebvClass:
- Species traits
- Ecosystem structure
representative_fundamental:
- 'Yes'
- 'Yes'
sensitive:
- 'No'
- 'No'
underpinNCP:
- 'No'
- 'No'
pristineValue:
- .na.real
- .na.real
allgoneValue:
- 0
- 0
notes:
- ''
- ''
