oldFilename: Freshwater_LPI.csv
indicatorName: Freshwater LPI
date: ''
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: Living Planet Index (freshwater)
ebvClass: Species populations
representative_fundamental: 'Yes'
sensitive: 'Yes'
underpinNCP: 'No'
pristineValue: .na.real
allgoneValue: 0
notes: ''
