oldFilename: BioTimeS.csv
indicatorName: BioTime Local Species Richness
date: ''
core_highlight_other: Highlight
whole_part: Whole
high_low: High
nameForPlot: Local species richness (BioTime)
ebvClass: Community composition
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: .na.real
allgoneValue: 0
notes: ''
