oldFilename: SR_weighted_900_2014_global.csv
indicatorName: PREDICTS SR-weighted mean local species richness (global)
date: 29/10/2018
core_highlight_other: Core
whole_part: Whole
high_low: High
nameForPlot: Local species richness (PREDICTS)
ebvClass: Community composition
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: ''
