oldFilename: FaurbyMammalGridOccurrences.csv
indicatorName: Terrestrial mammal grid cells
date: 05/04/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Mammalian range size
ebvClass: Species populations
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1298365.0
allgoneValue: 0
notes: ''
