oldFilename: mangrove_forest.csv
indicatorName: Area of mangrove forest cover (km2)
date: 23/02/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Mangrove forest area
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'Yes'
underpinNCP: 'No'
pristineValue: 346432.0369
allgoneValue: 0
notes: ''
