oldFilename: Ocean_NPP_PgC.csv
indicatorName: Ocean Net Primary Productivity (PgC)
date: 31/05/2017
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Marine NPP (remote sensing)
ebvClass: Ecosystem function
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'Yes'
pristineValue: .na.real
allgoneValue: 0
notes: Data emailed by Kazu Ichii 2017-05-31
