oldFilename: MSA_LU_CC.csv
indicatorName: MSA (hotspots)
date: 26/11/2018
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: Mean Species Abundance index (Hotspots)
ebvClass: Community composition
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: ''
