oldFilename: GLOBIO-results_LU_global.csv
indicatorName: Mean Species Abundance LU
date: 12/10/2018
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: ''
ebvClass: Community composition
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: .na.real
allgoneValue: .na.integer
notes: ''
