oldFilename: Percent_land_area_natural_habitat_revised2011data.csv
indicatorName: Percentage natural habitat extent
date: 23/02/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Natural habitat extent
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 100.0
allgoneValue: 0
notes: ''
