oldFilename: Surface_water_extent_Pekel.csv
indicatorName: Permanent surface water extent
date: 22/10/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Permanent surface water extent
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'Yes'
pristineValue: .na.real
allgoneValue: 0
notes: ''
