oldFilename: rli_forestspecialists.csv
indicatorName: Red List index (forest specialists)
date: 23/02/2018
core_highlight_other: Core
whole_part: Part
high_low: High
nameForPlot: RLI (forest specialists)
ebvClass: Species populations
representative_fundamental: 'No'
sensitive: 'Yes'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: ''
