oldFilename: RLI_pollut.csv
indicatorName: Red List Index (impacts of pollution)
date: 23/02/2018
core_highlight_other: Core
whole_part: Part
high_low: High
nameForPlot: Red List Index (impacts of pollution)
ebvClass: Species populations
representative_fundamental: 'No'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: ''
