oldFilename: RLI_utilization.csv
indicatorName: Red List Index (impacts of utilisation)
date: 23/02/2018
core_highlight_other: Core
whole_part: Part
high_low: High
nameForPlot: Red List Index (impacts of utilisation)
ebvClass: Species populations
representative_fundamental: 'No'
sensitive: 'No'
underpinNCP: 'Yes'
pristineValue: 1.0
allgoneValue: 0
notes: ''
