oldFilename: percent_primary_LUH2_900_2015.csv
indicatorName: Percentage primary LUH2
date: 01/12/2017
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Remaining primary vegetation
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 100.0
allgoneValue: 0
notes: ''
