oldFilename: Coarse_LUH2_hot_ipl.csv
indicatorName: Primary vegetation (Hotspots)
date: 14/11/2018
core_highlight_other: Other
whole_part: Part
high_low: High
nameForPlot: Remaining primary vegetation (Hotspots)
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1.0
allgoneValue: 0
notes: ''
