oldFilename: Trendy_Indicators_20181104_1860to2015.csv
indicatorName: cSoil (PgC)
date: 03/11/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Soil organic carbon (mechanistic models)
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 1320.14286
allgoneValue: 0
notes: Pristine value is for 1860, the first year of the model run
