oldFilename: AIM_LUCC_proportionalchange_grid_cell_2015_1970_190015.11.18.csv
indicatorName: Change in grid-cell species richness (all taxa) - AIM
date: 15/11/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Species richness per grid cell (AIM)
ebvClass: Community composition
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: .na.real
allgoneValue: 0
notes: ''
