oldFilename: TreeCoverChange_Song.csv
indicatorName: Tree cover change (Song)
date: 10/10/2018
core_highlight_other: Other
whole_part: Whole
high_low: High
nameForPlot: Tree cover
ebvClass: Ecosystem structure
representative_fundamental: 'Yes'
sensitive: 'No'
underpinNCP: 'No'
pristineValue: 62494.46494
allgoneValue: 0
notes: Pristine value is obtained by using Crowther et al. 2015
